### ISSUE TITLE
Rare error "cannot attach to a stopped container, start it first"

### ISSUE THREAD

**Issue by srigi** [michaelshobbs/dokku-app-predeploy-tasks#16]
There is a rare error as a result of race-condition when using `docker attach`. Other plugins was facing [this issue](https://github.com/sehrope/dokku-logging-supervisord/issues/5) as well.

Now I got this error in my application with **predeploy-tasks** plugin. Fix with commenting-out [affected line](https://github.com/michaelshobbs/dokku-app-predeploy-tasks/blob/f2f8b48d742df0be7143fc6d8566cb20e16a2569/pre-deploy#L35) worked for me.

[Trace](http://pastebin.com/ixxcTxvh) of the erroneous deploy.

**Comment by michaelshobbs** [comment]
I've not been able to recreate this with dokku 0.4.2 and master of this plugin. However, I think there is a simple fix. Patch coming.
