### ISSUE TITLE
Change to use DOKKU_SCALE file instead of SCALE

### ISSUE THREAD

**Issue by vijayviji** [michaelshobbs/dokku-app-predeploy-tasks#20]
Now, in DOKKU, the file for scaling used in DOKKU_SCALE.

**Comment by michaelshobbs** [comment]
I'd like to support both. PRs are welcomed.

**Comment by michaelshobbs** [comment]
To be clear `SCALE` came from [dokku-logging-supervisord](https://github.com/sehrope/dokku-logging-supervisord). I'm not sure of a clean way to do both. Perhaps we should use our own file here. Something like `PREDEPLOY_TASKS` perhaps?

**Comment by pythdasch** [comment]
Would be a good idea, because right now, this tasks are not running, I don't know why

**Comment by michaelshobbs** [comment]
This will be pre-empted by dokku/dokku#1836
